/**
 * Generated by Moaui DevTools
 * Created at 2024. 4. 22. 오후 6:56:51
 */

import React from "react";
import Moaui from "@midasit-dev/moaui";

const App: React.FC = () => {
	React.useEffect(() => {
		document.getElementById('Button-Run')?.addEventListener('click', () => {
			const text = (document.getElementById('textfieldv2-text') as HTMLInputElement).value;
			const color = (document.getElementById('colorpicker-color') as HTMLDivElement).getAttribute('data-temporary');
			const insert = (document.getElementById('textfieldv2-insert') as HTMLInputElement).value;
			const height = (document.getElementById('textfieldv2-height') as HTMLInputElement).value;
			if (color) {
				const inputJson = {
					text: text,
					color: JSON.parse(color),
					insert: insert,
					height: height,
				};
				const py_func = pyscript.interpreter.globals.get("text_to_plate_call");
				py_func(JSON.stringify(inputJson));
			}
		});
	}, []);

  return (
    <Moaui.Panel variant="box" relative width={600} height={600}>
      <Moaui.FloatingBox
        {...{
          x: 0,
          y: 0,
          width: "150px",
          height: "30px",
          guideBoxProps: { width: "inherit", height: "inherit", center: true },
        }}
      >
        <Moaui.TextFieldV2
          {...{
            id: "textfieldv2-text",
            autoFocus: false,
            type: "text",
            placeholder: "The text to convert",
            title: "text",
            titlePosition: "left",
            defaultValue: "Default Value",
            error: false,
            disabled: false,
            // value: '',
            width: "150px",
            titleXs: 3,
            inputXs: 9,
            height: "30px",
            textAlign: "left",
            multiline: false,
            rows: 1,
            maxRows: 1,
            gap: 1,
            inputAlign: "left",
            singleLineTitle: false,
          }}
        />
      </Moaui.FloatingBox>
      <Moaui.FloatingBox
        {...{
          x: 0,
          y: 40,
          width: "220px",
          height: "320px",
          guideBoxProps: { width: "inherit", height: "inherit", center: true },
        }}
      >
        <Moaui.ColorPicker
          {...{
						id: 'colorpicker-color',
            showRGB: true,
            direction: "column",
            width: "220px",
            height: "320px",
          }}
        />
      </Moaui.FloatingBox>
      <Moaui.FloatingBox
        {...{
					id: 'testflog',
          x: 0,
          y: 370,
          width: "150px",
          height: "30px",
          guideBoxProps: { width: "inherit", height: "inherit", center: true },
        }}
      >
        <Moaui.TextFieldV2
          {...{
            id: "textfieldv2-insert",
            autoFocus: false,
            type: "text",
            placeholder: "The insert point of the text (lower left corner)",
            title: "insert",
            titlePosition: "left",
            defaultValue: "Default Value",
            error: false,
            disabled: false,
            // value: "",
            width: "150px",
            titleXs: 3,
            inputXs: 9,
            height: "30px",
            textAlign: "left",
            multiline: false,
            rows: 1,
            maxRows: 1,
            gap: 1,
            inputAlign: "left",
            singleLineTitle: false,
          }}
        />
      </Moaui.FloatingBox>
      <Moaui.FloatingBox
        {...{
          x: 0,
          y: 410,
          width: "150px",
          height: "30px",
          guideBoxProps: { width: "inherit", height: "inherit", center: true },
        }}
      >
        <Moaui.TextFieldV2
          {...{
            id: "textfieldv2-height",
            autoFocus: false,
            type: "text",
            placeholder: "The height of the text",
            title: "height",
            titlePosition: "left",
            defaultValue: "Default Value",
            error: false,
            disabled: false,
            // value: "",
            width: "150px",
            titleXs: 3,
            inputXs: 9,
            height: "30px",
            textAlign: "left",
            multiline: false,
            rows: 1,
            maxRows: 1,
            gap: 1,
            inputAlign: "left",
            singleLineTitle: false,
          }}
        />
      </Moaui.FloatingBox>
      <Moaui.FloatingBox
        {...{
          x: 0,
          y: 450,
          width: "150px",
          height: "30px",
          guideBoxProps: { width: "inherit", height: "inherit", center: true },
        }}
      >
        <Moaui.Button
          {...{
						id: 'Button-Run',
            disabled: false,
            width: "150px",
            loading: false,
            variant: "contained",
            color: "normal",
          }}
        >
          Run
        </Moaui.Button>
      </Moaui.FloatingBox>
    </Moaui.Panel>
  );
};

//textfieldv2의 value sampleprops 제거
//전체다 id properties 추가 (코드 생성시)

export default App;
